[package]
name = "climb-graphql"
version = "0.1.0"
edition = "2021"

[dependencies]
async-graphql = "7.0.7"
async-graphql-axum = "7.0.7"
axum = "0.7.5"
config = "0.14.1"
deadpool = "0.12.1"
deadpool-postgres = { version = "0.14.0", features = ["serde"] }
postgis = "0.9.0"
postgres-types = { version = "0.2.8", features = ["derive"] }
regex = "1.11.1"
rust-s3 = "0.35.1"
serde = "1.0.215"
tokio = { version = "1.39.2", features = ["rt-multi-thread", "signal"] }
tokio-postgres = "0.7.12"
